"""Add consumption_rate to categories

Revision ID: 528908cd55a8
Revises: 89f485590365
Create Date: 2025-12-01 22:34:49.957709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528908cd55a8'
down_revision: Union[str, None] = '89f485590365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('consumption_rate', sa.Integer(), nullable=True, comment='Consumption rate in days'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'consumption_rate')
    # ### end Alembic commands ###
