"""Add product_metadata

Revision ID: 66b3106512d2
Revises: 001
Create Date: 2025-11-29 08:50:24.202252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b3106512d2'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('products')]

    if 'product_metadata' not in columns:
        op.add_column('products', sa.Column('product_metadata', sa.JSON(), nullable=True))
    
    if 'metadata' in columns:
        op.drop_column('products', 'metadata')

    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'product_metadata')
    # ### end Alembic commands ###
