"""Add hashed_password to User

Revision ID: 7da8085cd311
Revises: 66b3106512d2
Create Date: 2025-11-29 15:42:48.752266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da8085cd311'
down_revision: Union[str, None] = '66b3106512d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    
    # Update existing users with a default password "admin"
    # Hash for "admin" generated via passlib
    default_hash = "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW" 
    op.execute(f"UPDATE users SET hashed_password = '{default_hash}'")

    op.alter_column('users', 'hashed_password', nullable=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
