"""Add warehouse models and relationships

Revision ID: 89f485590365
Revises: 7da8085cd311
Create Date: 2025-11-30 21:06:01.379038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f485590365'
down_revision: Union[str, None] = '7da8085cd311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    warehouse_table = op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    
    # Create default warehouse
    connection = op.get_bind()
    from datetime import datetime
    connection.execute(
        sa.insert(warehouse_table).values(
            name="Default Warehouse",
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow()
        )
    )
    # Get the id of the default warehouse (assuming it's 1 since it's the first one)
    # But safer to query it if we could, but for now assuming 1 is safe for a fresh migration on existing data
    default_warehouse_id = 1

    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_table('warehouse_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_members_id'), 'warehouse_members', ['id'], unique=False)

    # Add columns as nullable first
    op.add_column('categories', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('inventory_actions', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('stock_batches', sa.Column('warehouse_id', sa.Integer(), nullable=True))

    # Backfill warehouse_id
    op.execute(f"UPDATE categories SET warehouse_id = {default_warehouse_id}")
    op.execute(f"UPDATE inventory_actions SET warehouse_id = {default_warehouse_id}")
    op.execute(f"UPDATE locations SET warehouse_id = {default_warehouse_id}")
    op.execute(f"UPDATE products SET warehouse_id = {default_warehouse_id}")
    op.execute(f"UPDATE stock_batches SET warehouse_id = {default_warehouse_id}")

    # Make columns not null
    op.alter_column('categories', 'warehouse_id', nullable=False)
    op.alter_column('inventory_actions', 'warehouse_id', nullable=False)
    op.alter_column('locations', 'warehouse_id', nullable=False)
    op.alter_column('products', 'warehouse_id', nullable=False)
    op.alter_column('stock_batches', 'warehouse_id', nullable=False)

    # Add foreign keys
    op.create_foreign_key(None, 'categories', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'inventory_actions', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'locations', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.create_foreign_key(None, 'products', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'stock_batches', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_batches', type_='foreignkey')
    op.drop_column('stock_batches', 'warehouse_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'warehouse_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'warehouse_id')
    op.drop_constraint(None, 'inventory_actions', type_='foreignkey')
    op.drop_column('inventory_actions', 'warehouse_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'warehouse_id')
    op.drop_index(op.f('ix_warehouse_members_id'), table_name='warehouse_members')
    op.drop_table('warehouse_members')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
